CREATE TABLE source
(
 poster_content VARCHAR NOT NULL,
 quantity  int ,
 price  decimal(3),
 email  VARCHAR,
 sales_rep VARCHAR,
 promo_code VARCHAR
);

INSERT INTO source(poster_content, quantity, price, email, sales_rep, promo_code) VALUES
('Luke Skywalker',1,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('C-3PO',2,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('R2-D2',3,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('Darth Vader',4,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('Leia Organa',5,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('Owen Lars',5,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('Beru Whitesun lars',5,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('R5-D4',1,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('Biggs Darklighter',2,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('Obi-Wan Kenobi Planets',3,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('Tatooine',4,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('Alderaan',5,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('Yavin IV',1,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('Hoth',2,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('Dagobah',3,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('Bespin',4,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('Endor',5,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('Naboo',1,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('Coruscant',2,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('Kamino Starships',3,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('CR90 corvette',4,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('Star Destroyer',5,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('Sentinel-class landing craft',1,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('Death Star',2,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('Millennium Falcon',3,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('Y-wing',4,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('X-wing',5,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('TIE Advanced x1',1,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('Executor',2,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('Rebel transport',3,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('Slave 1',4,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('Imperial shuttle',5,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('EF76 Nebulon-B escort frigate',1,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('Calamari Cruiser',2,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('A-wing',3,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('B-wing',4,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('Republic Cruiser',5,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('Droid control ship',1,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('Naboo fighter',2,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('Naboo Royal Starship',3,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('Scimitar',4,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('J-type diplomatic barge',5,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('AA-9 Coruscant freighter',1,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('Jedi starfighter',2,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('H-type Nubian yacht',3,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('Republic Assault ship',4,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('Solar Sailer',5,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('Trade Federation cruiser',1,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('Theta-class T-2c shuttle',2,10,'rekha.mallam@gmail.com','Rekha','freepos'),
('Republic attack cruiser',3,10,'rekha.mallam@gmail.com','Rekha','freepos');
